[build]
  command = "npm ci --include=optional && hugo --gc --minify -b $URL && curl -fsSL -o pagefind.tar.gz https://github.com/Pagefind/pagefind/releases/download/v1.5.2/pagefind-v1.5.2-x86_64-unknown-linux-musl.tar.gz && tar -xzf pagefind.tar.gz && chmod +x ./pagefind && ./pagefind --source 'public'"
  publish = "public"

[build.environment]
  HUGO_VERSION = "0.160.1"
  HUGO_ENABLEGITINFO = "true"
  NODE_ENV = "development"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL && curl -fsSL -o pagefind.tar.gz https://github.com/Pagefind/pagefind/releases/download/v1.5.2/pagefind-v1.5.2-x86_64-unknown-linux-musl.tar.gz && tar -xzf pagefind.tar.gz && chmod +x ./pagefind && ./pagefind --source 'public'"

[context.branch-deploy]
  command = "hugo --gc --minify -b $DEPLOY_PRIME_URL && curl -fsSL -o pagefind.tar.gz https://github.com/Pagefind/pagefind/releases/download/v1.5.2/pagefind-v1.5.2-x86_64-unknown-linux-musl.tar.gz && tar -xzf pagefind.tar.gz && chmod +x ./pagefind && ./pagefind --source 'public'"

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
